[package]
name = "spin0580/nucleard"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.3.0"
T = "osyrisrblx/t@3.1.1"

[server-dependencies]

[dev-dependencies]
